language: node_js
node_js:
- 12
- 13
before_script:
- npm install
script:
- npm run build
- npm run analyse
- npm run coverage
- npx stryker run
after_success:
- npm run codecov
env:
  global:
  - secure: T03QjwLJnGE7wSeIk0gOg0rt/pGOy0K3ArDLZWVCnPRlHhDHEZiX2zithEl8DcPF4MMgybSFjzmnlBoilZPDsQ3mcWlIiG08uCwROX+X3QE5etuyAO40OXn++z1QFcP0dIxmyZE4iuyTWp21CmuwtBuhhLRuhNgiAUcuKvpCL3orAXsGcCnfW+2e8EkzvN/2lQ6jdf355a8h10DHysGJ3/5OAzobkGdmet8Ai3z9eeybZsCts3fwjxpgvDhvV1ZSasflKkeFY6KIdvvcbReciUUOQA3tl+PrpMsrCO6ddWo94pLZj0oY9lyYIIKaxH7dG1XHeuO8SuDtXX95oaJAgusLuuF4wTA5GciGjxZTclR6v0NvPB/z5f/Fw9Ao1dn9LSqIVmoWndGPYZQXO2U/XOwaRGbnxbuSKBNMQ1rm9H/m0F12tjkQ26L0RwO5VwFTN0jA35Tx9iDiJiX73/eiLQEv+mPEjKhFnYHejzzIZ6MuwWUuHz6VvTLfDhULfIggUZIh/EKgLIHAwNWXTT9NrDIUv+6pJQ/lD2/Qxe8mT//S/gjPH70IVW09HfQDKWtX/h2I+Vk67kPiZSmOoWfq9RJb/Ujq0OHB2k8I5CkDJSzbGyHLxYY6YTSxID90f1RgYzaHM3u/pjRErkBo2IeJ4M5ckZB9K50KCDIuwg//vVk=
