language: node_js
node_js:
  - 12

before_script:
  - npm install

script:
  - npm run build
  - npm run analyse
  - npm run coverage
  - npx stryker run

after_success:
  - npm run codecov

env:
  global:
    secure: hTT61NnqbbGAFIJw9BaBqFg4z1jKqOO/t09BcJiVDbDPGjgW1vuGvOtp++gM/HPBrIvWrlJmVY1QWHLb6/Gyfu9NaBKm0sPUM+TR6nO5yS9o3hE7xqL77bqy3nqQwFVo4FaVgOsD0HnW1VRV6C+gs+5Yw4jplNF2lIFFuOJPmOEs6vJBX0Vs/o1t9aff3yzAEceCf3p6H63VUR3wDE7Gk7veXPfkbF/M3HKw8BOuicjwNAwcJ8wMR8ecnpw18eN2DuXAUM76Ju4wblvJskZXhBsCJKfRidhY0+TFzM3RqLwin1eqS1GbL8WLdyCpOW7mBG3FsmZrWH0aIqnp2O9697ffzpdAtbAT24kNhOrHdrCaGWSI7uOJsINwrkz4mq6o8G4JkrLGTbEPOkFnUZgsVvQ0e4rIRa2/z6PCl0F0d3HaxtIEkik63xt4P6TFvWCumHyWxmwYxgDdfYgMGtbg4gQBk+Wg+eb+wadWj0aRhY/iySI73h+vIoyWmV1jP4tlQnLCdcRIcFnlxQBLXsdfs6LSjoGy8H0tP/p+PIzmK3zNK4SHadCgoI9Il+KC+S5R2Z68vrhb3r03aSReqv/JPJkTQsmgCKewfAI53ycxUWf3gDjP27YQffKOOs5k+azXpBx+rZAYNcilXmXJil3OAK72+bQpfe+hjkUD2I8aqZU=